version: 2

project_name: exe

before:
  hooks:
    - go mod tidy

builds:
  - id: exe
    binary: exe
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/prjvvl/exe/internal/version.Version={{.Tag}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: exe
    ids: [exe]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: prjvvl
    name: exe

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
