name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: release-please
    if: ${{ needs.release-please.outputs.pr != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_JSON: ${{ needs.release-please.outputs.pr }}
        run: |
          pr_number="$(echo "$PR_JSON" | jq -r '.number')"
          gh pr merge --merge --repo "${{ github.repository }}" "$pr_number"
